# Generated by Django 2.0.5 on 2018-05-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0007_auto_20180507_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='resumeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
