# Generated by Django 2.0.2 on 2018-04-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Administrator'), ('O', 'Owner')], default='S', max_length=1)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('Phone_Number', models.PositiveIntegerField(max_length=10)),
                ('Qualifications', models.TextField()),
                ('Email_Address', models.EmailField(max_length=50)),
                ('Facebook_ID', models.URLField(max_length=75)),
                ('Languages_Spoken', models.TextField()),
                ('Instruments_Played', models.TextField()),
                ('Parent_Name', models.CharField(max_length=50)),
                ('Parent_Email', models.EmailField(max_length=50)),
                ('parent_phoneNum', models.PositiveIntegerField(max_length=10, verbose_name="Parent's phone number")),
                ('Student_Type', models.CharField(choices=[('New', 'New'), ('Old', 'Old')], default='New', max_length=3)),
            ],
        ),
    ]
