# Generated by Django 2.0.3 on 2018-04-28 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music_school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(verbose_name='Date of Birth')),
                ('Phone_Number', models.PositiveIntegerField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='OldUserModel',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete='cascade', related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
