# Generated by Django 2.0.4 on 2018-05-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0002_auto_20180428_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingsModel',
            fields=[
                ('bookingID', models.AutoField(primary_key=True, serialize=False)),
                ('studentID', models.IntegerField()),
                ('teacherID', models.IntegerField()),
                ('startingDate', models.DateField()),
                ('startingTime', models.TimeField()),
                ('lessonDuration', models.IntegerField(choices=[(30, '30 Minutes'), (60, '60 Minutes')], default=30)),
                ('instrumentFocus', models.CharField(max_length=30)),
                ('isRecurring', models.BooleanField(default=False)),
                ('lessonRepeat', models.CharField(choices=[(1, 'Weekly'), (0.5, 'Fornightly'), (2, 'Twice per Week'), (3, 'Thrice per Week')], default=None, max_length=20)),
                ('secondaryLessonDay', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=None, max_length=20)),
                ('secondaryLessonTime', models.TimeField(default=None)),
                ('tertiaryLessonDay', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=None, max_length=20)),
                ('tertiaryLessonTime', models.TimeField(default=None)),
            ],
        ),
    ]
