# Generated by Django 2.0.5 on 2018-05-07 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0003_bookingsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingsModelRecurring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonRepeat', models.CharField(default=None, max_length=20)),
                ('secondaryLessonDay', models.CharField(default=None, max_length=20)),
                ('secondaryLessonTime', models.TimeField(default=None)),
                ('tertiaryLessonDay', models.CharField(default=None, max_length=20)),
                ('tertiaryLessonTime', models.TimeField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='isRecurring',
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='lessonRepeat',
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='secondaryLessonDay',
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='secondaryLessonTime',
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='studentID',
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='tertiaryLessonDay',
        ),
        migrations.RemoveField(
            model_name='bookingsmodel',
            name='tertiaryLessonTime',
        ),
        migrations.AddField(
            model_name='bookingsmodel',
            name='studentUsername',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingsmodel',
            name='lessonDuration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='bookingsmodelrecurring',
            name='bookingID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='music_school.bookingsModel'),
        ),
    ]
