# Generated by Django 2.0.5 on 2018-05-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0004_auto_20180507_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsmodel',
            name='startingTime',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='lessonRepeat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='secondaryLessonDay',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='secondaryLessonTime',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='tertiaryLessonDay',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='tertiaryLessonTime',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
