# Generated by Django 2.0.5 on 2018-05-07 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0005_auto_20180507_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingsmodelrecurring',
            name='id',
        ),
        migrations.AddField(
            model_name='bookingsmodelrecurring',
            name='recurringID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='bookingID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='music_school.bookingsModel'),
        ),
    ]
