# Generated by Django 2.0.5 on 2018-05-07 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_school', '0006_auto_20180507_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsmodelrecurring',
            name='bookingID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music_school.bookingsModel'),
        ),
    ]
